### ISSUE TITLE
Fenstergrösse/-eigenschaften auf Mac OS X

### ISSUE THREAD

**Issue by tbreuss** [ahueber/iperf-GUI#4]
Unter Mac OS X verhalten sich die Fenster sehr eigenartig. Einerseits habe ich die volle Fensterbreite (was auf dem Raspberry Sinn macht), andrerseits verschwinden die Fenster aber bei gewissen Aktionen (z.B. wenn ich das Numpad schliesse). Zur Abhilfe lasse ich mir die Windows mittels s->show() anzeigen. Hier sollte noch geprüft werden, ob das Handling der QWidgets korrekt ist.

**Comment by ahueber** [comment]
Lösung: Auf Linux umsteigen ;-)
