### ISSUE TITLE
Einheitliche Sprache

### ISSUE THREAD

**Issue by tbreuss** [ahueber/iperf-GUI#7]
Labels und Buttons sind noch uneinheitlich benannt. Ich schlage vor, dass wir Deutsch als Standard vorsehen. Wir können uns aber auch auf Englisch einigen. Es muss "nur" einheitlich sein.

Folgendes sollte geändert werden:

welcomescreen.cpp:
- Exit --> Beenden

server.cpp:
- Start --> Starten
- Close --> Schliessen

client.cpp:
- Start --> Starten
- Close --> Schliessen

numpad.cpp:
- Done --> (Vorschlag?)

Und ebenfalls auch das Menu sollte angepasst werden:
- Hide iperf
- Hide others
- Show all
- Quit iperf

**Comment by ahueber** [comment]
Sprache ist jetzt auf allen Button deutsch. Was meinst du mit dem Menu? Ist das wieder etwas das nur Apple hat?
